export const FILE_TYPE_IDS = {
  PURCHASE_INVOICE_SA1_RETAIL: 1,
  EXECUTED_DEAL_PACKAGE_SA2_RETAIL: 2,
  ACCOUNTING_INVOICE_BILL_OF_SALE_SA2: 3,
  OTHER_RETAIL: 4,
  OTHER_WHOLESALE: 6,
  FACTORY_INVOICE_SA1_RETAIL: 9,
  EXECUTED_DEAL_PACKAGE_SA2_WHOLESALE: 10,
  FACTORY_INVOICE_SA1_WHOLESALE: 14,
  PURCHASE_INVOICE_SA1_WHOLESALE: 16
};
